"""MODEL-RECORD.md generation.

The markdown rendering keeps the archive legible without the tool
(ADR 0001): a human with ``ls`` and a pager can read what a model is.
It is generated from the JSON record and never parsed back.
"""

import re

from llm_preserver.records import ArtifactEntry, ModelRecord

_UNKNOWN = "unknown"
_CONTROL_CHARS = re.compile(r"[\x00-\x08\x0b-\x1f\x7f-\x9f]")
_LINE_BREAKS = re.compile(r"[\n\t]")


def clean_text(text: str, *, single_line: bool = False) -> str:
    """Replace terminal control characters with U+FFFD.

    Record fields and directory names are untrusted input — an archive
    may have been authored elsewhere — so anything echoed to a terminal
    must not carry ANSI/OSC escape sequences. The full C0 and C1
    control ranges are replaced; only newline and tab survive.

    Args:
        text: Raw string from a record or the filesystem.
        single_line: Also collapse newline/tab to a space — required
            for one-line output (table rows, error messages), where a
            line break would let hostile input forge whole rows.

    Returns:
        The sanitized string.
    """
    cleaned = _CONTROL_CHARS.sub("�", text)
    if single_line:
        cleaned = _LINE_BREAKS.sub(" ", cleaned)
    return cleaned


def _value(field: object) -> str:
    """Render a nullable record field for display.

    Always single-line: record scalars are hub-derived, and a value
    carrying a newline (``"apache-2.0\\n## forged"``) must not inject
    markdown structure into the generated document.
    """
    return _UNKNOWN if field is None else clean_text(str(field), single_line=True)


def _cell(text: str) -> str:
    """Sanitize an untrusted value for a markdown table cell.

    Single-line plus pipe-escaping, so a hostile value cannot forge
    rows or columns in the provenance table.
    """
    return clean_text(text, single_line=True).replace("|", "\\|")


def _artifact_section(artifact: ArtifactEntry) -> list[str]:
    """Render one artifact as a markdown section."""
    lines = [
        f"## Artifact: {artifact.format}",
        "",
        f"- Quantization: {_value(artifact.quantization)}",
        f"- Source repo: {_value(artifact.source_repo)}",
        f"- Revision (commit): {_value(artifact.revision)}",
        f"- Download date: {_value(artifact.download_date)}",
        f"- Runtime tested: {_value(artifact.runtime_tested)}",
        f"- Provenance: {artifact.provenance}",
        "",
    ]
    if artifact.files:
        lines += [
            "| File | SHA256 | Size (bytes) | Source | Provenance |",
            "| --- | --- | --- | --- | --- |",
        ]
        lines += [
            f"| {_cell(entry.path)} | {_value(entry.sha256)} "
            f"| {_value(entry.size)} | {entry.source} | {_value(entry.provenance)} |"
            for entry in artifact.files
        ]
        lines.append("")
    return lines


_BASE_SOURCE_PROSE = {
    "card": "as declared by this repo's model card",
    "asserted": "as recorded by the curator",
    "migrated": "carried over from the directory this repo's files used to sit under",
}


def _lineage_lines(record: ModelRecord) -> list[str]:
    """The lineage sentence, or nothing when no claim exists.

    ADR 0003 gave every repo its own directory, so the filesystem no
    longer says that a quant derives from a model. This line is where
    that survives for a reader with ``ls`` and ``cat`` and no tool —
    ADR 0001's durability test, which the old nested layout passed
    structurally and this layout has to pass in words.
    """
    if record.base_model is None:
        return []
    how = _BASE_SOURCE_PROSE.get(record.base_model_source or "", "")
    suffix = f" ({how})" if how else ""
    return [f"- Derived from: {clean_text(record.base_model)}{suffix}"]


def render_model_record(record: ModelRecord, *, file_header: bool = True) -> str:
    """Render a model record as markdown.

    Args:
        record: The record to render.
        file_header: Include the generated-file warning header. True
            for MODEL-RECORD.md on disk; False for terminal output
            (``show``), where "edit the JSON, not this file" would be
            nonsense.

    Returns:
        Markdown text.
    """
    header = (
        [
            "<!-- GENERATED by llm-preserver from model-record.json.",
            "     Edit model-record.json, not this file. -->",
            "",
        ]
        if file_header
        else []
    )
    capabilities = ", ".join(record.capabilities) if record.capabilities else None
    lines = [
        *header,
        f"# {clean_text(record.name)}",
        "",
        f"- Hub id: {clean_text(record.hub_id)}",
        *_lineage_lines(record),
        f"- Roles: {', '.join(record.roles) or '(no role)'}",
        f"- Capabilities: {_value(capabilities)}",
        f"- Pipeline tag: {_value(record.pipeline_tag)}",
        f"- License: {_value(record.license)}",
        f"- Parameters: {_value(record.parameter_count)}",
        f"- Context length: {_value(record.context_length)}",
        f"- Notes: {_value(record.notes)}",
        "",
    ]
    for artifact in record.artifacts:
        lines += _artifact_section(artifact)
    return "\n".join(lines).rstrip("\n") + "\n"
